from kedro.pipeline import Pipeline, node, pipeline
from .nodes import (
    fetch_openaire_researchproduct,
    land_openaire_rel_researchproduct_authors,
    land_openaire_rel_researchproduct_contributors,
    land_openaire_rel_researchproduct_instances,
    land_openaire_rel_researchproduct_pids,
    land_openaire_rel_researchproduct_sources,
    land_openaire_rel_researchproduct_subjects,
    land_openaire_rel_researchproduct_originalid,
    land_openaire_researchproduct,
)

def create_pipeline(**kwargs) -> Pipeline:
    return pipeline([
        node(
            name="fetch_openaire_researchproduct",
            func=fetch_openaire_researchproduct,
            inputs=[
                "params:openaire_fetch_options.filter_param",
                "params:openaire_fetch_options.filter_value",
                "params:openaire_fetch_options.access_token",
                "params:openaire_fetch_options.refresh_token",
                "params:fetch_options.env",
            ],
            outputs=[
                "raw/openaire/researchproduct#parquet",
                "raw/openaire/researchproduct_dev#parquet",
                ],
        ),
        node(
            name="land_openaire_rel_researchproduct_authors",
            func=land_openaire_rel_researchproduct_authors,
            inputs="raw/openaire/researchproduct#parquet",
            outputs="ldg/openaire/rel_researchproduct_authors",
        ),
        node(
            name="land_openaire_rel_researchproduct_instances",
            func=land_openaire_rel_researchproduct_instances,
            inputs="raw/openaire/researchproduct#parquet",
            outputs=[
                "ldg/openaire/rel_researchproduct_instances",
                "ldg/openaire/rel_researchproduct_alternateidentifiers",
            ]
        ),
        node(
            name="land_openaire_rel_researchproduct_originalid",
            func=land_openaire_rel_researchproduct_originalid,
            inputs="raw/openaire/researchproduct#parquet",
            outputs="ldg/openaire/rel_researchproduct_originalid"
        ),
        node(
            name="land_openaire_rel_researchproduct_pids",
            func=land_openaire_rel_researchproduct_pids,
            inputs="raw/openaire/researchproduct#parquet",
            outputs="ldg/openaire/rel_researchproduct_pids"
        ),
        node(
            name="land_openaire_rel_researchproduct_sources",
            func=land_openaire_rel_researchproduct_sources,
            inputs="raw/openaire/researchproduct#parquet",
            outputs="ldg/openaire/rel_researchproduct_sources"
        ),
        node(
            name="land_openaire_rel_researchproduct_subjects",
            func=land_openaire_rel_researchproduct_subjects,
            inputs="raw/openaire/researchproduct#parquet",
            outputs="ldg/openaire/rel_researchproduct_subjects"
        ),
        node(
            name="land_openaire_rel_researchproduct_contributors",
            func=land_openaire_rel_researchproduct_contributors,
            inputs="raw/openaire/researchproduct#parquet",
            outputs="ldg/openaire/rel_researchproduct_contributors"
        ),
        node(
            name="land_openaire_researchproduct",
            func=land_openaire_researchproduct,
            inputs=[
                "params:openaire_fetch_options.filter_param",
                "params:openaire_fetch_options.filter_value",
                "raw/openaire/researchproduct#parquet",
            ],
            outputs="ldg/openaire/researchproduct"
        ),
    ], tags="openaire_researchproduct")
