from kedro.pipeline import Pipeline, node, pipeline
from .nodes import (
    fetch_author_openalex,
    fetch_work_openalex,
    land_author_openalex,
    land_author2affiliation_openalex,
    land_author2topic_openalex,
    land_work_openalex,
    land_work2apc_list_openalex,
    land_work2apc_paid_openalex,
    land_work2authorships_openalex,
    land_work2ids_openalex,
    land_work2concepts_openalex,
    land_work2corresponding_author_ids_openalex,
    land_work2primary_topic_openalex,
    land_work2primary_location_openalex,
    land_work2referenced_works_openalex,
    land_work2topics_openalex,
    land_work2location_openalex,
)


def create_pipeline(**kwargs) -> Pipeline:
    return pipeline([
        node(
            name="fetch_work_dimensions_openalex",
            func=fetch_work_dimensions_openalex,
            inputs=[],
            outputs=[
                "raw/openalex/worktype#parquet",
                "raw/openalex/language#parquet",
                "raw/openalex/license#parquet",
                ],
            ),
        node(
            name="land_work_dimensions_openalex",
            func=land_work_dimensions_openalex,
            inputs=[
                "raw/openalex/worktype#parquet",
                "raw/openalex/language#parquet",
                "raw/openalex/license#parquet",
            ],
            outputs=[
                "ldg/openalex/worktype",
                "ldg/openalex/language",
                "ldg/openalex/license",
                ],
            ),
        node(
            name="fetch_work_openalex",
            func=fetch_work_openalex,
            inputs=[
                "params:openalex_fetch_options.institution_ror",
                "params:fetch_options.env",
            ],
            outputs=["raw/openalex/work#parquet","raw/openalex/work_dev#parquet"],
            ),
        node(
            name="fetch_author_openalex",
            func=fetch_author_openalex,
            inputs=[
                "params:openalex_fetch_options.institution_ror",
                "params:fetch_options.env",
            ],
            outputs="raw/openalex/author#parquet",
            ),
        node(
            name="land_author_openalex",
            func=land_author_openalex,
            inputs='raw/openalex/author#parquet',
            outputs='ldg/openalex/author'
            ),
        node(
            name="land_author2affiliation_openalex",
            func=land_author2affiliation_openalex,
            inputs='raw/openalex/author#parquet',
            outputs='ldg/openalex/author2affiliation'
            ),
        node(
            name="land_author2topic_openalex",
            func=land_author2topic_openalex,
            inputs='raw/openalex/author#parquet',
            outputs='ldg/openalex/author2topic'
            ),
        node(
            name="land_work_openalex",
            func=land_work_openalex,
            inputs='raw/openalex/work#parquet',
            outputs='ldg/openalex/work'
            ),
        node(
            name="land_work2apc_list_openalex",
            func=land_work2apc_list_openalex,
            inputs='raw/openalex/work#parquet',
            outputs='ldg/openalex/work2apc_list'
            ),
        node(
            name="land_work2apc_paid_openalex",
            func=land_work2apc_paid_openalex,
            inputs='raw/openalex/work#parquet',
            outputs='ldg/openalex/work2apc_paid'
            ),
        node(
            name="land_work2authorships_openalex",
            func=land_work2authorships_openalex,
            func=land_work2authorships_openalex,
            inputs='raw/openalex/work#parquet',
            outputs=['ldg/openalex/work2author', 'ldg/openalex/author2institution']
            ),
        node(
            name="land_work2ids_openalex",
            inputs='raw/openalex/work#parquet',
            outputs=['ldg/openalex/work2author', 'ldg/openalex/author2institution']
            ),
        node(
            name="land_work2ids_openalex",
            func=land_work2ids_openalex,
            inputs='raw/openalex/work#parquet',
            outputs='ldg/openalex/work2ids'
            ),
        node(
            name="land_work2concepts_openalex",
            func=land_work2concepts_openalex,
            inputs='raw/openalex/work#parquet',
            outputs='ldg/openalex/work2concepts'
            ),
        node(
            name="land_work2corresponding_author_ids_openalex",
            func=land_work2corresponding_author_ids_openalex,
            inputs='raw/openalex/work#parquet',
            outputs='ldg/openalex/work2corresponding_author_ids'
            ),
        node(
            name="land_work2primary_topic_openalex",
            func=land_work2primary_topic_openalex,
            inputs='raw/openalex/work#parquet',
            outputs='ldg/openalex/work2primary_topics'
            ),
        node(
            name="land_work2primary_location_openalex",
            func=land_work2primary_location_openalex,
            inputs='raw/openalex/work#parquet',
            outputs='ldg/openalex/work2primary_location'
            ),
        node(
            name="land_work2referenced_works_openalex",
            func=land_work2referenced_works_openalex,
            inputs='raw/openalex/work#parquet',
            outputs='ldg/openalex/work2referenced_works'
            ),
        node(
            name="land_work2topics_openalex",
            func=land_work2topics_openalex,
            inputs='raw/openalex/work#parquet',
            outputs='ldg/openalex/work2topics'
            ),
        node(
            name="land_work2location_openalex",
            func=land_work2location_openalex,
            inputs='raw/openalex/work#parquet',
            outputs='ldg/openalex/work2location'
            )
], tags="openalex"
)
